sudo: false
language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
before_install: gem install bundler
script: bundle exec rake
notifications:
  email:
    recipients:
      - jpriddle@me.com
    on_success: never
    on_failure: always
